# name is not mandatory
- name: install and run nginx 
  hosts: mongodb
  become: yes # this will give root access
  tasks:
  - name: install nginx
    ansible.builtin.yum:
      name: httpd
      state: latest
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
