- name: variables from files
  hosts: localhost # managing the sever itself
  vars_files:
  - variables.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: " we are learning {{COURSE}} , duration is: {{DURATION}} By: {{NAME}} AND MY {{STUDENT:}}"