- name: simple conditions
  hosts: localhost
  vars:
    NAME: DevOps
  tasks:
  - name: run this if name is DevOps
    ansible.builtin.debug:
      msg: "hello {{NAME}}"
    when: {{NAME}} == "DevOps"