- name: loops example
  hosts: localhost # you no need to give user name and password through command line
  tasks:  
  - name: print the names
    ansible.builtin.debug:
      msg: "hello {{item}}, how are you"
    loop:
    - shivakumar
    - saikumar
    - raheem 
    - john 