- name: install packages
  hosts: localhost
  become: true
  tasks:
  - name: install packages
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed  
    loop:
    - nginx
    - postmap 