- name: install packages
  hosts: localhost
  become: true
  tasks:
    - name: install or remove packages based on state
      ansible.builtin.yum:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
      ignore_errors: true
      loop:
        - { name: 'nginx', state: 'absent' }
        - { name: 'postfix', state: 'installed' }
        - { name: 'cyrus-sasl-plain', state: 'absent' }
        - { name: 'mailx', state: 'installed' }
