- name: install packages
  hosts: localhost
  become: true
  tasks:
  - name: install packages
    ansible.builtin.yum:
    ignore_errors:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'nginx' , state: 'absent'}
    - {name: 'postfix' , state: 'installed'}
    - {name: 'cyrus-sasl-plain', state: 'absent'}
    - {name: 'mailx', state: 'installed'}
    
    